In [1]:
import pandas as pd

data = pd.read_csv(r"C:\Users\Nithyapriya\OneDrive\jpg----\Documents\python\pythonproject\student_performance_data.csv")

print(data)

     StudentID  Gender  Age  StudyHoursPerWeek  AttendanceRate   GPA  \
0            1    Male   24                 37           90.75  3.47
1            2  Female   22                 37           74.90  2.32
2            3    Male   22                 10           53.36  2.38
3            4    Male   24                 10           70.26  3.46
4            5    Male   18                 19           74.87  2.31
..         ...     ...  ...                ...             ...   ...
495        496    Male   22                 37           76.61  2.97
496        497    Male   23                 11           56.29  3.20
497        498  Female   20                  6           56.64  3.20
498        499    Male   22                 18           57.18  2.05
499        500  Female   24                 21           96.99  2.64

           Major PartTimeJob ExtraCurricularActivities
0           Arts         Yes                        No
1      Education          No                        No
2       Business          No                        No
3        Science         Yes                        No
4      Education         Yes                        No
..           ...         ...                       ...
495      Science          No                        No
496      Science          No                        No
497      Science          No                       Yes
498     Business          No                       Yes
499  Engineering          No                        No

[500 rows x 9 columns]

In [2]:
data.head(10)

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities
0,1,Male,24,37,90.75,3.47,Arts,Yes,No
1,2,Female,22,37,74.90,2.32,Education,No,No
2,3,Male,22,10,53.36,2.38,Business,No,No
3,4,Male,24,10,70.26,3.46,Science,Yes,No
4,5,Male,18,19,74.87,2.31,Education,Yes,No
5,6,Female,20,17,86.01,2.47,Business,Yes,No
6,7,Male,19,21,55.33,3.93,Arts,No,No
7,8,Male,18,14,57.00,2.51,Education,No,No
8,9,Male,19,9,63.18,3.32,Business,No,No
9,10,Female,24,1,63.32,3.96,Engineering,Yes,Yes

In [3]:
data.tail(10)

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities
490,491,Female,23,4,98.65,3.45,Engineering,Yes,Yes
491,492,Male,21,26,79.01,2.21,Arts,Yes,Yes
492,493,Male,18,29,62.71,2.45,Education,Yes,No
493,494,Female,22,34,76.09,3.41,Engineering,No,No
494,495,Male,24,23,67.13,2.11,Business,No,Yes
495,496,Male,22,37,76.61,2.97,Science,No,No
496,497,Male,23,11,56.29,3.20,Science,No,No
497,498,Female,20,6,56.64,3.20,Science,No,Yes
498,499,Male,22,18,57.18,2.05,Business,No,Yes
499,500,Female,24,21,96.99,2.64,Engineering,No,No

In [4]:
data.describe()

        StudentID         Age  StudyHoursPerWeek  AttendanceRate        GPA
count  500.000000  500.000000         500.000000      500.000000  500.00000
mean   250.500000   20.956000          19.876000       74.990380    2.98516
std    144.481833    2.000517          11.471347       14.565917    0.56362
min      1.000000   18.000000           1.000000       50.010000    2.00000
25%    125.750000   19.000000          10.000000       62.607500    2.48750
50%    250.500000   21.000000          20.500000       75.730000    3.00000
75%    375.250000   23.000000          30.000000       87.220000    3.48000
max    500.000000   24.000000          39.000000       99.970000    3.99000

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StudentID                  500 non-null    int64
 1   Gender                     500 non-null    object
 2   Age                        500 non-null    int64
 3   StudyHoursPerWeek          500 non-null    int64
 4   AttendanceRate             500 non-null    float64
 5   GPA                        500 non-null    float64
 6   Major                      500 non-null    object
 7   PartTimeJob                500 non-null    object
 8   ExtraCurricularActivities  500 non-null    object
dtypes: float64(2), int64(3), object(4)
memory usage: 35.3+ KB

In [6]:
def add(a,b):
    c=a+b
    return c

k=add(5,7)
print(k)

12

In [7]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()



data["Major"] = label_encoder.fit_transform(data["Major"])
data

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities
0,1,Male,24,37,90.75,3.47,0,Yes,No
1,2,Female,22,37,74.90,2.32,2,No,No
2,3,Male,22,10,53.36,2.38,1,No,No
3,4,Male,24,10,70.26,3.46,4,Yes,No
4,5,Male,18,19,74.87,2.31,2,Yes,No
...,...,...,...,...,...,...,...,...,...
495,496,Male,22,37,76.61,2.97,4,No,No
496,497,Male,23,11,56.29,3.20,4,No,No
497,498,Female,20,6,56.64,3.20,4,No,Yes
498,499,Male,22,18,57.18,2.05,1,No,Yes
499,500,Female,24,21,96.99,2.64,3,No,No

In [8]:
empty_cells = data.isnull()
print(empty_cells)

     StudentID  Gender    Age  StudyHoursPerWeek  AttendanceRate    GPA  \
0        False   False  False              False           False  False
1        False   False  False              False           False  False
2        False   False  False              False           False  False
3        False   False  False              False           False  False
4        False   False  False              False           False  False
..         ...     ...    ...                ...             ...    ...
495      False   False  False              False           False  False
496      False   False  False              False           False  False
497      False   False  False              False           False  False
498      False   False  False              False           False  False
499      False   False  False              False           False  False

     Major  PartTimeJob  ExtraCurricularActivities
0    False        False                      False
1    False        False                      False
2    False        False                      False
3    False        False                      False
4    False        False                      False
..     ...          ...                        ...
495  False        False                      False
496  False        False                      False
497  False        False                      False
498  False        False                      False
499  False        False                      False

[500 rows x 9 columns]

In [9]:
empty_cells = data.isnull().sum()
print(empty_cells)

StudentID                    0
Gender                       0
Age                          0
StudyHoursPerWeek            0
AttendanceRate               0
GPA                          0
Major                        0
PartTimeJob                  0
ExtraCurricularActivities    0
dtype: int64

In [10]:
X11 = float(data["Age"].mean())
print(X11)

20.956

In [14]:
x1=data["StudyHoursPerWeek"].mean()
print(x1)

19.876

In [12]:
x2=data["AttendanceRate"].mean()
x2

np.float64(74.99038)

In [13]:
x3=data["GPA"].mean()
x3

np.float64(2.9851600000000005)

In [15]:
x6=data["Gender"].mode()
x6

0    Female
Name: Gender, dtype: object

In [16]:
data["Age"].fillna(X11,inplace=True)
data["AttendanceRate"].fillna(x1,inplace=True)

C:\Users\Nithyapriya\AppData\Local\Temp\ipykernel_49120\2262192560.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Age"].fillna(X11,inplace=True)
C:\Users\Nithyapriya\AppData\Local\Temp\ipykernel_49120\2262192560.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["AttendanceRate"].fillna(x1,inplace=True)

In [17]:
empty_cells = data.isnull().sum()
print(empty_cells)

StudentID                    0
Gender                       0
Age                          0
StudyHoursPerWeek            0
AttendanceRate               0
GPA                          0
Major                        0
PartTimeJob                  0
ExtraCurricularActivities    0
dtype: int64

In [22]:
import pandas as pd 

data=[1,3,4,5,6]
s=pd.Series([data])
s

0    [1, 3, 4, 5, 6]
dtype: object

In [23]:
import pandas as pd

# Load your dataset
data = pd.read_csv("student_performance_data.csv")

# Convert into dictionary pattern (like your tamil/english/maths example)
student = {
    "StudentID": data["StudentID"].head(3).tolist(),
    "Gender": data["Gender"].head(3).tolist(),
    "Age": data["Age"].head(3).tolist(),
    "StudyHoursPerWeek": data["StudyHoursPerWeek"].head(3).tolist(),
    "AttendanceRate": data["AttendanceRate"].head(3).tolist(),
    "GPA": data["GPA"].head(3).tolist(),
    "Major": data["Major"].head(3).tolist(),
    "PartTimeJob": data["PartTimeJob"].head(3).tolist(),
    "ExtraCurricularActivities": data["ExtraCurricularActivities"].head(3).tolist()
}

# Show dictionary values
print(student)

# Convert dictionary into DataFrame (like your screenshot)
dataframe = pd.DataFrame(student)
print(dataframe)

{'StudentID': [1, 2, 3], 'Gender': ['Male', 'Female', 'Male'], 'Age': [24, 22, 22], 'StudyHoursPerWeek': [37, 37, 10], 'AttendanceRate': [90.75, 74.9, 53.36], 'GPA': [3.47, 2.32, 2.38], 'Major': ['Arts', 'Education', 'Business'], 'PartTimeJob': ['Yes', 'No', 'No'], 'ExtraCurricularActivities': ['No', 'No', 'No']}
   StudentID  Gender  Age  StudyHoursPerWeek  AttendanceRate   GPA      Major  \
0          1    Male   24                 37           90.75  3.47       Arts
1          2  Female   22                 37           74.90  2.32  Education
2          3    Male   22                 10           53.36  2.38   Business

  PartTimeJob ExtraCurricularActivities
0         Yes                        No
1          No                        No
2          No                        No

In [24]:
dataframe=pd.DataFrame(student)
dataframe

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities
0,1,Male,24,37,90.75,3.47,Arts,Yes,No
1,2,Female,22,37,74.90,2.32,Education,No,No
2,3,Male,22,10,53.36,2.38,Business,No,No

In [26]:
dataframe["StudentID"]

0    1
1    2
2    3
Name: StudentID, dtype: int64

In [27]:
print(dataframe.loc[1])

StudentID                            2
Gender                          Female
Age                                 22
StudyHoursPerWeek                   37
AttendanceRate                    74.9
GPA                               2.32
Major                        Education
PartTimeJob                         No
ExtraCurricularActivities           No
Name: 1, dtype: object

In [28]:
print(dataframe.loc[[1]])

   StudentID  Gender  Age  StudyHoursPerWeek  AttendanceRate   GPA      Major  \
1          2  Female   22                 37            74.9  2.32  Education

  PartTimeJob ExtraCurricularActivities
1          No                        No

In [29]:
l=[[1],45]
l[0][0]

1

In [30]:
print(dataframe.loc[[0,1]])

   StudentID  Gender  Age  StudyHoursPerWeek  AttendanceRate   GPA      Major  \
0          1    Male   24                 37           90.75  3.47       Arts
1          2  Female   22                 37           74.90  2.32  Education

  PartTimeJob ExtraCurricularActivities
0         Yes                        No
1          No                        No

In [31]:
import pandas as pd

# Load your dataset
data = pd.read_csv("student_performance_data.csv")

# Build dictionary with a few rows (like your ram/ragul/krish example)
student = {
    "StudentID": data["StudentID"].head(3).tolist(),
    "Gender": data["Gender"].head(3).tolist(),
    "Age": data["Age"].head(3).tolist(),
    "StudyHoursPerWeek": data["StudyHoursPerWeek"].head(3).tolist(),
    "AttendanceRate": data["AttendanceRate"].head(3).tolist(),
    "GPA": data["GPA"].head(3).tolist(),
    "Major": data["Major"].head(3).tolist(),
    "PartTimeJob": data["PartTimeJob"].head(3).tolist(),
    "ExtraCurricularActivities": data["ExtraCurricularActivities"].head(3).tolist()
}

# Create DataFrame with custom index (stu1, stu2, stu3)
df = pd.DataFrame(student, index=["1", "2", "3"])
print(df)

   StudentID  Gender  Age  StudyHoursPerWeek  AttendanceRate   GPA      Major  \
1          1    Male   24                 37           90.75  3.47       Arts
2          2  Female   22                 37           74.90  2.32  Education
3          3    Male   22                 10           53.36  2.38   Business

  PartTimeJob ExtraCurricularActivities
1         Yes                        No
2          No                        No
3          No                        No

In [33]:
df.loc[["1"]]

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities
1,1,Male,24,37,90.75,3.47,Arts,Yes,No

In [34]:
ages = pd.Series([25, 30, 35])

print(ages)

0    25
1    30
2    35
dtype: int64

In [35]:
ages[0]

np.int64(25)